# Welcome to Jekyll!
#
# This config file is used to configure your site.

# Site Settings
locale                   : "en-US"
title                    : "Jack Davis Portfolio"
title_separator          : "-"
subtitle                 : "Mechanical Engineering Portfolio"
name                     : "Jack Davis"
description              : "Mechanical Engineering Student Portfolio"
url                      : "https://github.io"
baseurl                  : ""

# Theme Settings
minimal_mistakes_skin    : "dark"
remote_theme             : "mmistakes/minimal-mistakes@4.24.0"

# Site Author
author:
  name             : "Jack Davis"
  avatar           : "https://placehold.co"
  bio              : "Mechanical Engineering Student | Software & Automation"
  location         : "Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"

# Site Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
